# Generated by Django 4.1 on 2022-10-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0002_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority_level',
            field=models.IntegerField(default=0),
        ),
    ]
