# Generated by Django 4.0 on 2022-09-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='the_app.priority'),
            preserve_default=False,
        ),
    ]
