# Generated by Django 4.1.3 on 2022-12-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_whatever',
            field=models.BooleanField(default=False),
        ),
    ]
