# Generated by Django 4.1 on 2022-12-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athing',
            name='name',
            field=models.CharField(default='Computer', max_length=255),
            preserve_default=False,
        ),
    ]
